/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param role The role of the author of this message.
 * @param content The contents of the message
 */


data class ChatCompletionResponseMessage (

    /* The role of the author of this message. */
    @Json(name = "role")
    val role: ChatCompletionResponseMessage.Role,

    /* The contents of the message */
    @Json(name = "content")
    val content: kotlin.String

) {

    /**
     * The role of the author of this message.
     *
     * Values: system,user,assistant
     */
    enum class Role(val value: kotlin.String) {
        @Json(name = "system") system("system"),
        @Json(name = "user") user("user"),
        @Json(name = "assistant") assistant("assistant");
    }
}

