/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * Up to 4 sequences where the API will stop generating further tokens. 
 *
 */
@Deprecated("This class is deprecated, please use Array<String> instead.")
data class CreateChatCompletionRequestStop (private val value: Any) {
    init {
        require(value is String || value is Array<*>) {
            "value must be initialized with a String or an Array of Strings"
        }
    }

    fun getValue(): Any {
        return value
    }
}
