/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models

import org.openapi.client.kotlin.openai.models.CreateCompletionResponseChoicesInnerLogprobs

import com.squareup.moshi.Json

/**
 * 
 *
 * @param text 
 * @param index 
 * @param logprobs 
 * @param finishReason 
 */


data class CreateCompletionResponseChoicesInner (

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "index")
    val index: kotlin.Int? = null,

    @Json(name = "logprobs")
    val logprobs: CreateCompletionResponseChoicesInnerLogprobs? = null,

    @Json(name = "finish_reason")
    val finishReason: kotlin.String? = null

)

