/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param flagged 
 * @param categories 
 * @param categoryScores 
 */


data class CreateModerationResponseResultsInner (

    @Json(name = "flagged")
    val flagged: kotlin.Boolean,

    @Json(name = "categories")
    val categories: CreateModerationResponseResultsInnerCategories,

    @Json(name = "category_scores")
    val categoryScores: CreateModerationResponseResultsInnerCategoryScores

)

