/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models

import org.openapi.client.kotlin.openai.models.ChatCompletionResponseMessage

import com.squareup.moshi.Json

/**
 * 
 *
 * @param index 
 * @param message 
 * @param finishReason 
 */


data class CreateChatCompletionResponseChoicesInner (

    @Json(name = "index")
    val index: kotlin.Int? = null,

    @Json(name = "message")
    val message: ChatCompletionResponseMessage? = null,

    @Json(name = "finish_reason")
    val finishReason: kotlin.String? = null

)

