/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param `object` 
 * @param document 
 * @param score 
 */


data class CreateSearchResponseDataInner (

    @Json(name = "object")
    val `object`: kotlin.String? = null,

    @Json(name = "document")
    val document: kotlin.Int? = null,

    @Json(name = "score")
    val score: java.math.BigDecimal? = null

)

