/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param index 
 * @param `object` 
 * @param embedding 
 */


data class CreateEmbeddingResponseDataInner (

    @Json(name = "index")
    val index: kotlin.Int,

    @Json(name = "object")
    val `object`: kotlin.String,

    @Json(name = "embedding")
    val embedding: kotlin.collections.List<java.math.BigDecimal>

)

