/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param document 
 * @param text 
 * @param label 
 */


data class CreateClassificationResponseSelectedExamplesInner (

    @Json(name = "document")
    val document: kotlin.Int? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "label")
    val label: kotlin.String? = null

)

