/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `object` 
 * @param model 
 * @param `data` 
 */


data class CreateSearchResponse (

    @Json(name = "object")
    val `object`: kotlin.String? = null,

    @Json(name = "model")
    val model: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.collections.List<CreateSearchResponseDataInner>? = null

)

