/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models

import org.openapi.client.kotlin.openai.models.CreateAnswerResponseSelectedDocumentsInner

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `object` 
 * @param model 
 * @param searchModel 
 * @param completion 
 * @param answers 
 * @param selectedDocuments 
 */


data class CreateAnswerResponse (

    @Json(name = "object")
    val `object`: kotlin.String? = null,

    @Json(name = "model")
    val model: kotlin.String? = null,

    @Json(name = "search_model")
    val searchModel: kotlin.String? = null,

    @Json(name = "completion")
    val completion: kotlin.String? = null,

    @Json(name = "answers")
    val answers: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "selected_documents")
    val selectedDocuments: kotlin.collections.List<CreateAnswerResponseSelectedDocumentsInner>? = null

)

