/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param `object` 
 * @param deleted 
 */


data class DeleteFileResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "object")
    val `object`: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean

)

