/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapi.client.kotlin.openai.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param url 
 * @param b64Json 
 */


data class ImagesResponseDataInner (

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "b64_json")
    val b64Json: kotlin.String? = null

)

